//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMenu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int idproduct { get; set; }
        public int quantity { get; set; }
        public double totalprice { get; set; }
        public int idorder { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
