//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMenu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        public product()
        {
            this.orderdetail = new HashSet<orderdetail>();
        }
        [Required(ErrorMessage = "This field is required")]
        public int idproduct { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string name { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public double price { get; set; }
        public string details { get; set; }
        public string AddPError { get; set; }

        public virtual ICollection<orderdetail> orderdetail { get; set; }
    }
}
