//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickMenu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class quickmenusubEntities : DbContext
    {
        public quickmenusubEntities(string conn)
            : base(conn)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<employee> employee { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<orderdetail> orderdetail { get; set; }
        public DbSet<pagestyle> pagestyle { get; set; }
    }
}
